title: Lollipop

email: l6p.io@hotmail.com

description: The better experience for performance testing

url: "https://l6p.io"

baseurl: ""

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

google:
  gtag: "G-M645ESKSD0"
